import { Award, CircleDot, Goal, UsersRound } from "lucide-react";
import { DataSourceBadge, Leaderboard, PageIntro, SectionHeading, TeamMark } from "@/components/football/FootballUI";
import { getFootballData } from "@/lib/api-football/cache";
import { competitionParams, responseOf } from "@/lib/api-football/page-data";

export const metadata = { title: "Players" };

function CardLeaders({ entries, color, field, label }) {
  return <div className="space-y-2">{entries.slice(0, 6).map((entry, index) => { const stat = entry.statistics?.[0]; return <div className="flex items-center gap-3 rounded-2xl bg-surface-soft p-3" key={entry.player?.id ?? index}><span className={`flex size-8 items-center justify-center rounded-xl text-xs font-black ${color}`}>{index + 1}</span><TeamMark size="sm" team={stat?.team} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{entry.player?.name}</p><p className="truncate text-[0.66rem] text-ink-muted">{stat?.team?.name}</p></div><div className="text-right"><p className="font-black">{stat?.cards?.[field] ?? 0}</p><p className="text-[0.58rem] uppercase tracking-wider text-ink-muted">{label}</p></div></div>; })}</div>;
}

export default async function PlayersPage({ searchParams }) {
  const competition = await competitionParams(searchParams);
  const [assistsData, scorersData, yellowData, redData] = await Promise.all(["top-assists", "top-scorers", "top-yellow-cards", "top-red-cards"].map((endpoint) => getFootballData(endpoint, competition, { allowStale: true })));
  const assists = responseOf(assistsData), scorers = responseOf(scorersData), yellow = responseOf(yellowData), red = responseOf(redData);
  return <div className="space-y-7"><PageIntro eyebrow="Player performance" title="The people moving the numbers." description="Four API-Football leaderboards arrive with complete player statistical blocks—no extra profile call is needed to build a rich ranking." actions={<DataSourceBadge meta={assistsData.meta} />} /><section className="grid gap-5 xl:grid-cols-2"><div className="surface-panel p-5 sm:p-6"><SectionHeading description="Top finishers by total goals." title="Golden boot race" /><Leaderboard metric="goals" players={scorers} limit={10} /></div><div className="surface-panel p-5 sm:p-6"><SectionHeading description="Chance creators ranked by assists." title="Playmaker race" /><Leaderboard players={assists} limit={10} /></div></section><section className="grid gap-5 xl:grid-cols-2"><div className="surface-panel p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl bg-warning/10 text-warning"><Award className="size-4" /></span><div><h2 className="font-black">Yellow cards</h2><p className="text-xs text-ink-muted">Disciplinary leaderboard</p></div></div><CardLeaders color="bg-warning/10 text-warning" entries={yellow} field="yellow" label="yellow" /></div><div className="surface-panel p-5 sm:p-6"><div className="mb-5 flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-2xl bg-danger/10 text-danger"><CircleDot className="size-4" /></span><div><h2 className="font-black">Red cards</h2><p className="text-xs text-ink-muted">Dismissal leaderboard</p></div></div><CardLeaders color="bg-danger/10 text-danger" entries={red} field="red" label="red" /></div></section><section className="surface-flat flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><UsersRound className="size-5 text-brand-strong" /><div><p className="font-black">Full player search remains available</p><p className="text-xs text-ink-muted">Use the API explorer for profiles, squads, seasons and team history.</p></div></div><a className="button-secondary" href="/explorer">Explore player endpoints <Goal className="size-4" /></a></section></div>;
}

